# Generated by Django 5.0.4 on 2024-04-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('CL', 'Classification'), ('SG', 'Segmentation'), ('BB', 'BoundingBox')], max_length=2)),
                ('version_string', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
