# Generated by Django 5.0.4 on 2024-06-04 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='xrayprediction',
            old_name='image',
            new_name='original_image',
        ),
        migrations.RemoveField(
            model_name='xrayimage',
            name='diagnosing_doctor',
        ),
        migrations.AddField(
            model_name='xrayprediction',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xrayprediction',
            name='prediction_type',
            field=models.CharField(choices=[('DET', 'Detection'), ('SEG', 'Segmentation')], default='SEG', max_length=3),
        ),
        migrations.CreateModel(
            name='PredictedXRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_file', models.ImageField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosing_doctor', models.ForeignKey(limit_choices_to={'user_type': 'Dr'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_predicted_xray_image', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'Pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_predicted_xray_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='xrayprediction',
            name='predicted_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='predictions', to='inference_api.predictedxrayimage'),
        ),
    ]
