# Generated by Django 5.0.4 on 2024-06-05 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_api', '0004_alter_predictedxrayimage_diagnosing_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayprediction',
            name='original_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_image_to_predictions', to='inference_api.xrayimage'),
        ),
        migrations.AlterField(
            model_name='xrayprediction',
            name='predicted_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_image_to_predictions', to='inference_api.predictedxrayimage'),
        ),
    ]
