# Generated by Django 5.0.4 on 2024-06-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_api', '0005_alter_xrayprediction_original_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayprediction',
            name='predicted_image',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_image_to_predictions', to='inference_api.predictedxrayimage'),
            preserve_default=False,
        ),
    ]
